openapi: 3.2.0
info:
  title: Patient Access Immunization API
  description: Patient Access Endpoints for FHIR Resources
  version: '1.0'
servers:
- url: https://dev-int-api-gw.centene.com/fhir/v4/patientaccess
tags:
- name: Immunization
paths:
  /Immunization:
    get:
      tags:
      - Immunization
      summary: Search all resources of type Immunization based on a set of criteria
      operationId: searchImmunization
      parameters:
      - name: patient
        in: query
        description: The patient for the vaccination record
        schema:
          type: string
      - name: _revinclude
        in: query
        schema:
          type: string
          x-consoleDefault: application/json
        x-consoleDefault: application/json
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Immunization-search'
        '400':
          description: Bad request
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: invalid
                  details:
                    text: Invalid or badly formed Immunization ID .
        '401':
          description: Unauthorized
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Unauthorized
                  details:
                    text: You are not authorized to view this Immunization.
        '403':
          description: Forbidden
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: forbidden
                  details:
                    text: You are not allowed to view this Immunization.
        '404':
          description: Not Found
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Found
                  details:
                    text: No Immunization found with the provided ID.
        '500':
          description: InternalServerError
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: fatal
                  code: exception
                  details:
                    text: Internal server error. Please try again later
        '429':
          description: Too Many Requests
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Too Many Requests
                  details:
                    text: Too Many Requests for Immunization with the provided ID.
        '501':
          description: Not Implemented
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Implemented
                  details:
                    text: The request for Immunization is Not Implemented
        '502':
          description: Bad gateway
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Bad gateway
                  details:
                    text: Bad gateway
        '503':
          description: Service Unavailable
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Service Unavailable
                  details:
                    text: Service Unavailable
        '504':
          description: Gateway Timeout
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Gateway Timeout
                  details:
                    text: Gateway Timeout
      security:
      - Bearer: []
  /Immunization/{id}:
    get:
      tags:
      - Immunization
      summary: Read the current state of the resource
      operationId: readImmunization
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Immunization'
        '400':
          description: Bad request
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: invalid
                  details:
                    text: Invalid or badly formed Immunization ID .
        '401':
          description: Unauthorized
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Unauthorized
                  details:
                    text: You are not authorized to view this Immunization.
        '403':
          description: Forbidden
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: forbidden
                  details:
                    text: You are not allowed to view this Immunization.
        '404':
          description: Not Found
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Found
                  details:
                    text: No Immunization found with the provided ID.
        '500':
          description: InternalServerError
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: fatal
                  code: exception
                  details:
                    text: Internal server error. Please try again later
        '429':
          description: Too Many Requests
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Too Many Requests
                  details:
                    text: Too Many Requests for Immunization with the provided ID.
        '501':
          description: Not Implemented
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Implemented
                  details:
                    text: The request for immunization is Not Implemented
        '502':
          description: Bad gateway
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Bad gateway
                  details:
                    text: Bad gateway
        '503':
          description: Service Unavailable
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Service Unavailable
                  details:
                    text: Service Unavailable
        '504':
          description: Gateway Timeout
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Gateway Timeout
                  details:
                    text: Gateway Timeout
      security:
      - Bearer: []
components:
  schemas:
    Immunization:
      required:
      - id
      - meta
      - occurrenceDateTime
      - patient
      - primarySource
      - resourceType
      - status
      - text
      - vaccineCode
      type: object
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        meta:
          required:
          - profile
          type: object
          properties:
            profile:
              type: array
              items:
                type: object
                properties: {}
        text:
          required:
          - div
          - status
          type: object
          properties:
            status:
              minLength: 1
              type: string
            div:
              minLength: 1
              type: string
        status:
          minLength: 1
          type: string
        vaccineCode:
          required:
          - coding
          type: object
          properties:
            coding:
              minItems: 1
              uniqueItems: true
              type: array
              items:
                required:
                - code
                - display
                - system
                type: object
                properties:
                  system:
                    minLength: 1
                    type: string
                  code:
                    minLength: 1
                    type: string
                  display:
                    minLength: 1
                    type: string
        patient:
          required:
          - display
          - reference
          type: object
          properties:
            reference:
              minLength: 1
              type: string
            display:
              minLength: 1
              type: string
        occurrenceDateTime:
          minLength: 1
          type: string
        primarySource:
          type: boolean
      description: ''
    Immunization-search:
      required:
      - entry
      - id
      - link
      - meta
      - resourceType
      - total
      - type
      type: object
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        meta:
          required:
          - lastUpdated
          type: object
          properties:
            lastUpdated:
              minLength: 1
              type: string
        type:
          minLength: 1
          type: string
        total:
          type: number
        link:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - relation
            - url
            type: object
            properties:
              relation:
                minLength: 1
                type: string
              url:
                minLength: 1
                type: string
        entry:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - fullUrl
            type: object
            properties:
              fullUrl:
                minLength: 1
                type: string
              resource:
                required:
                - id
                - meta
                - occurrenceDateTime
                - patient
                - primarySource
                - resourceType
                - status
                - text
                - vaccineCode
                type: object
                properties:
                  resourceType:
                    minLength: 1
                    type: string
                  id:
                    minLength: 1
                    type: string
                  meta:
                    required:
                    - profile
                    type: object
                    properties:
                      profile:
                        type: array
                        items:
                          type: object
                          properties: {}
                  text:
                    required:
                    - div
                    - status
                    type: object
                    properties:
                      status:
                        minLength: 1
                        type: string
                      div:
                        minLength: 1
                        type: string
                  status:
                    minLength: 1
                    type: string
                  vaccineCode:
                    required:
                    - coding
                    type: object
                    properties:
                      coding:
                        minItems: 1
                        uniqueItems: true
                        type: array
                        items:
                          required:
                          - code
                          - display
                          - system
                          type: object
                          properties:
                            system:
                              minLength: 1
                              type: string
                            code:
                              minLength: 1
                              type: string
                            display:
                              minLength: 1
                              type: string
                  patient:
                    required:
                    - display
                    - reference
                    type: object
                    properties:
                      reference:
                        minLength: 1
                        type: string
                      display:
                        minLength: 1
                        type: string
                  occurrenceDateTime:
                    minLength: 1
                    type: string
                  primarySource:
                    type: boolean
      description: ''
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
