openapi: 3.2.0
info:
  title: Provider Carrier Entity Search (PCES) Custom Query…
  description: PCES Description
  contact:
    email: provider_search_support@centene.com
  version: 0.0.6
servers:
- url: https://dev-int-api-gw.centene.com/pces
  description: Dev
- url: https://prod.api.centene.com/incoming/dev/pces
  description: Dev DMZ
- url: https://test-int-api-gw.centene.com/pces
  description: Test
- url: https://prod.api.centene.com/incoming/test/pces
  description: Test DMZ
- url: https://api-gateway-01.centene.com/pces
  description: Prod
- url: https://prod.api.centene.com/incoming/pces
  description: Prod DMZ
tags:
- name: custom-query-validator
paths:
  /custom-query-validator:
    post:
      tags:
      - custom-query-validator
      summary: providerCarrierEntitySearchCustomQueryValidator
      operationId: providerCarrierEntitySearchCustomQueryValidatorUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
              - $ref: '#/components/schemas/CarrierEntityRequest'
            examples:
              query exmaple:
                description: ''
                value:
                  customQuery:
                    value:
                      field: location.name
                      value: Walgreens
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/Responses'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    MatchedListsCondition:
      title: MatchedListsCondition
      type: object
      properties:
        filter:
          type: string
        list:
          type: string
    CarrierEntityRequest:
      title: CarrierEntityRequest
      type: object
      properties:
        aggs:
          type: array
          items:
            $ref: '#/components/schemas/Aggregation'
        customQuery:
          $ref: '#/components/schemas/Condition'
        from:
          type: integer
          format: int32
        matchedLists:
          type: array
          items:
            $ref: '#/components/schemas/MatchedListsCondition'
        relevancy:
          type: array
          items:
            $ref: '#/components/schemas/RelevancyCondition'
        size:
          type: integer
          format: int32
    RelevancyCondition:
      title: RelevancyCondition
      type: object
      anyOf:
      - $ref: '#/components/schemas/RelevancyByDistanceCondition'
      - $ref: '#/components/schemas/AvailabilityCondition'
    Condition:
      type: object
    RelevancyByDistanceCondition:
      title: RelevancyByDistanceCondition
      properties:
        decay:
          type: string
        field:
          type: string
        minDistanceScore:
          type: string
        offset:
          type: string
        origin:
          type: string
        scale:
          type: string
      allOf:
      - $ref: '#/components/schemas/RelevancyCondition'
      - title: RelevancyByDistanceCondition
        type: object
        properties:
          decay:
            type: string
          field:
            type: string
          minDistanceScore:
            type: string
          offset:
            type: string
          origin:
            type: string
          scale:
            type: string
    AggregationValues:
      title: AggregationValues
      type: object
      properties:
        field:
          type: string
        size:
          type: integer
          format: int32
    AggregationType:
      title: AggregationType
      type: object
      properties:
        filter:
          $ref: '#/components/schemas/Condition'
        valuesAgg:
          $ref: '#/components/schemas/AggregationValues'
    Aggregation:
      title: Aggregation
      type: object
      properties:
        aggType:
          $ref: '#/components/schemas/AggregationType'
        aggs:
          type: array
          items:
            $ref: '#/components/schemas/Aggregation'
        name:
          type: string
    Responses:
      title: Response
      type: object
      properties:
        totalHits:
          type: number
        queryTime:
          type: string
        results:
          type: array
          items:
            type: string
        aggs:
          type: array
          items:
            type: string
        scrollId:
          type: string
    AvailabilityCondition:
      title: AvailabilityCondition
      allOf:
      - $ref: '#/components/schemas/RelevancyCondition'
      - title: AvailabilityCondition
        type: object
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
externalDocs:
  description: Centene Search DSL Documentation
  url: https://centene-search-dsl.ckp-dev.centene.com/
